#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace EOS.Unity.Editor
{
    /// <summary>Breaks the codegen deadlock where a stale generated <c>.gen.cs</c> under <c>Assets/EOS.Generated</c> fails to compile after a system or method signature change: on a failed compile whose errors point at a generated file it resets that file to a harmless stub so the assembly compiles, letting the normal <c>[DidReloadScripts]</c> regeneration rebuild it from the current types.</summary>
    [InitializeOnLoad]
    static class EosGeneratedCodegenRecovery
    {
        const string GeneratedDir = "Assets/EOS.Generated/";
        const string GeneratedSuffix = ".gen.cs";
        const string Tag = "[EOS]";

        const string Stub =
            "// <auto-generated>\n" +
            "// EOS codegen was reset after a stale compile error. It regenerates on the next script reload.\n" +
            "// </auto-generated>\n";

        static readonly HashSet<string> Pending = new HashSet<string>();

        static EosGeneratedCodegenRecovery()
        {
            CompilationPipeline.assemblyCompilationFinished -= OnAssemblyCompilationFinished;
            CompilationPipeline.assemblyCompilationFinished += OnAssemblyCompilationFinished;
        }

        static void OnAssemblyCompilationFinished(string assemblyPath, CompilerMessage[] messages)
        {
            try
            {
                if (messages == null) return;

                foreach (var message in messages)
                {
                    if (message.type != CompilerMessageType.Error) continue;

                    var path = ToGeneratedProjectPath(message.file);
                    if (path == null) continue;

                    Reset(path);
                }
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"{Tag} codegen recovery failed: {ex.Message}");
            }
        }

        static string ToGeneratedProjectPath(string file)
        {
            if (string.IsNullOrEmpty(file)) return null;

            var normalized = file.Replace('\\', '/');
            if (!normalized.EndsWith(GeneratedSuffix, StringComparison.Ordinal)) return null;

            var index = normalized.IndexOf(GeneratedDir, StringComparison.Ordinal);
            if (index < 0) return null;

            return normalized.Substring(index);
        }

        static void Reset(string projectPath)
        {
            if (!File.Exists(projectPath)) return;
            if (File.ReadAllText(projectPath) == Stub) return;

            File.WriteAllText(projectPath, Stub);
            Debug.LogWarning($"{Tag} reset stale generated file {projectPath} (its signature changed and broke compilation); it will regenerate on the next reload.");

            if (Pending.Add(projectPath))
                EditorApplication.delayCall += FlushPending;
        }

        static void FlushPending()
        {
            try
            {
                foreach (var path in Pending)
                    AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
                Pending.Clear();
                AssetDatabase.Refresh();
            }
            catch (Exception ex)
            {
                Pending.Clear();
                Debug.LogWarning($"{Tag} codegen recovery re-import failed: {ex.Message}");
            }
        }
    }
}
#endif
